services:
  backend:
    build:
      context: ./server
    image: backend
    container_name: backend
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
    networks:
      - my-network

  frontend:
    build:
      context: ./client
    image: frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
