# Use the official Node.js image as the base image
FROM node:20-alpine


RUN apk add --no-cache curl
# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

EXPOSE 8000

# Copy the rest of the application code
COPY . .

# Start the Node.js server
CMD ["npm", "start"]
